### ISSUE TITLE
[help wanted] issue with tags, added double value at a time

### ISSUE THREAD

**Issue by boredcodebyk** [boredcodebyk/minttask#11]
so, im still working around with the tag feature. currently using the following function to make add the word in an array after user enters space or comma. it works as intended but it added the work in the array twice. if anyone has some ideas/suggestion, please share below.

![image](https://github.com/boredcodebyk/minttask/assets/25322315/fe2b142d-7eb2-48f6-a2ab-90c06cdb2239)

```dart
TextField(
  controller: _tagController,
  decoration: const InputDecoration(border: InputBorder.none, hintText: "Add tags..."),
  onChanged: (value) {
    var previousText0 = '';
    final previousText = previousText0;
    previousText0 = value;
    if (value.length == 1 &&
        [" ", ","].contains(value)) {
      _tagController.clear();
      return;
    }
    if (value.length >
        previousText.length) {
      // Add case
      final newChar = value[value.length - 1];
      if ([" ", ","].contains(newChar)) {
        final targetString =
            value.substring(0, value.length - 1);
        if (targetString.isNotEmpty) {
          tagsValue.add(targetString);
          _tagController.clear();
        }
      }
    }
    print(tagsValue);
  },
)
```

**Comment by boredcodebyk** [comment]
`value` is String which is the value from the text field which is passed in onChange() as parameter whenever there is change in textfield. and this is flutter's textfield, not any 3rd party package

**Comment by cosmicsarthak** [comment]
I suppose this is correct, have you tried to hot restart again? as the Logic is correct.

**Comment by boredcodebyk** [comment]
yes. yes i did.

**Comment by cosmicsarthak** [comment]
Is the same thing happening for multiple words input?

**Comment by boredcodebyk** [comment]
you see, there is no point in entering multiple words at once because, after every word, user will add a space or comma just like how tags work in social networks

**Comment by cosmicsarthak** [comment]
It is for some reason running the `onChanged` method twice...
You can have a look here to make this text detection and matching faster, that might be causing this issue.
- https://blog.0xba1.xyz/0522/dart-flutter-regexp/

I don't have my laptop right now, I'll try to check back again once I get back home.

**Comment by cosmicsarthak** [comment]
> you see, there is no point in entering multiple words at once because, after every word, user will add a space or comma just like how tags work in social networks

Yup, but its inefficient way for text matching as , it will force re render of the whole Input Widget again and again, as the onChanged is Stateful, so regular expressions would make your logic foolproof. But I believe your current logic is correct, though inefficient but it should work.

**Comment by cosmicsarthak** [comment]
> It is for some reason running the `onChanged` method twice...
> You can have a look here to make this text detection and matching faster, that might be causing this issue.
> - https://blog.0xba1.xyz/0522/dart-flutter-regexp/
> 
> I don't have my laptop right now, I'll try to check back again once I get back home.

Also check out this thread and try to implement onChange with RegEx
- https://github.com/flutter/flutter/issues/73178

**Comment by boredcodebyk** [comment]
Taking different approach
